services:
  # Backend-Service
  - type: web
    name: household-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: household-db
          property: connectionString

  # Frontend-Service
  - type: web
    name: household-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://household-backend.onrender.com

# MySQL Datenbank
databases:
  - name: household-db
    plan: free
    type: mysql
